spring.application.name=backend

## MySQL Configs
#spring.datasource.url = jdbc:mysql://localhost:3306/tech_assess
#spring.datasource.username = mustafa
#spring.datasource.password = Mm01022350739@

# PostgreSQL Configs
spring.datasource.url = jdbc:postgresql://localhost:5432/tech_assess
spring.datasource.username = postgres
spring.datasource.password = postgres

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = false
spring.jpa.properties.hibernate.format_sql = true